version: '3.3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password_for_database
      MYSQL_DATABASE: ui1_world_rowing
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
